# Generated by Django 5.0.2 on 2024-02-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinflip',
            old_name='time_temps',
            new_name='time_temp',
        ),
    ]
